name: technology-data
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9,<3.11
  - pip
  - snakemake-minimal
  - pandas>=1.1.0
  - numpy
  - beautifulsoup4
  - xlrd
  - scipy
  - openpyxl<=3.1.0
  - packaging

  - pip:
    - tabula-py
    - currencyconverter
