name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2.1.1 
      with:
          python-version: 3.8
          environment-file: environment.yaml
          activate-environment: technology-data
          auto-activate-base: false
    - name: Test snakemake workflow
      shell: bash -l {0}
      run: |
        snakemake --cores all -f compile_cost_assumptions
